FROM node:alpine AS build

WORKDIR /usr/client
RUN npm install --global pm2

COPY package*.json yarn.lock ./

RUN npm install --production

COPY ./ ./

RUN npm run build

EXPOSE 3000

CMD ["pm2-runtime","npm", "--", "start"]
