version: '3.7'

services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - app-network
  client:
    build: client
    container_name: client
    depends_on:
      - api
    networks:
      - app-network
  api:
    build: server
    container_name: api
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - database:/data/db
    networks:
      - app-network

volumes:
  database:

networks:
  app-network:
    driver: bridge
