version: '3.7'

services:
  client:
    build: client
    container_name: client
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./client:/client
  api:
    build: server
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - mongo
    volumes:
      - ./server:/server
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - database:/data/db

volumes:
  database:
